### ISSUE TITLE
Server names are not displayed properly in the overlay.

### ISSUE THREAD

**Issue by esskayesss** [ElijahPepe/BDThemes#2]
When hovering over the server svg, the name is not properly rendered. This doesn't happen with folder names. I guess you need to update the font color somewhere.

![image](https://user-images.githubusercontent.com/77633131/113512873-5b9a6980-9584-11eb-913f-00bc37210fdc.png)

![image](https://user-images.githubusercontent.com/77633131/113512917-a0be9b80-9584-11eb-814f-18a0f7617993.png)

**Comment by ElijahPepe** [comment]
https://github.com/ElijahPepe/BetterDiscordAddons/issues/3#issuecomment-841765443
